project: 
  type: website
  execute-dir: project

execute: 
  freeze: auto
  message: false

website: 
  page-navigation: true
  title: "ANIM5502 2022 Data analyses" 
  site-url: "https://jdberson.github.io/ANIM5502_2022" 
  repo-url: https://github.com/jdberson/ANIM5502_2022 
  repo-actions: [issue]
  
  page-footer:
    right: "This page is built with using [Quarto](https://quarto.org/) using tips from an [openscapes tutorial](https://openscapes.github.io/quarto-website-tutorial/)."
    left: "&copy; CC-By JD Berson, 2022"
    
  sidebar:
    style: "docked"
    search: true
    pinned: true
    tools: 
      - icon: github
        menu: 
          - text: Source code
            url: https://code.com
          - text: Report a bug
            url: https://bugs.com
    contents: 
      - href: index.qmd
        text: Welcome
      - section: dung_beetles/dung_beetles_index.qmd
        contents:
          - dung_beetles/dung_beetles_data_cleaning.qmd
          - dung_beetles/dung_beetles_data_exploration.qmd
          - dung_beetles/dung_beetles_data_modelling.qmd


format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    code-link: true
    df-print: paged
    toc: true
    editor: visual